server:
  port: 8989
management:
  port: 9222
spring:
  application:
    name: hystrix-turbine


applications: consulhystrixclient
turbine:
  aggregator:
    clusterConfig: ${applications}
  appConfig: ${applications}
