server:
  port: 5566
spring:
  application:
    name: zuul-gateway
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: configserver
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  routes:
    api-a:
      path: /app/**
      serviceId: hello-service
    api-b:
      path: /consumer/**
      serviceId: app-consumer


